[project]
name = "anp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-connect>=0.3.5",
    "any>=0.0.2",
    "asyncio>=3.4.3",
    "fastapi>=0.116.1",
    "openai>=1.95.1",
    "uvicorn>=0.35.0",
]
